#!/bin/bash

# Setup script for The Commons frontend environment variables

echo "Setting up environment variables for The Commons frontend..."

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists. Backing up to .env.local.backup"
    cp .env.local .env.local.backup
fi

# Create .env.local with default development values
cat > .env.local << EOF
# Environment Variables for The Commons Frontend
# Generated by setup-env.sh

# API Configuration
VITE_API_BASE_URL=http://localhost:8000

# Feature Flags
VITE_COMPASS_ENABLED=true
VITE_PRINCIPLES_DOC_MODE=true
VITE_DELEGATION_ENABLED=true
VITE_USE_HARDCODED_DATA=true
VITE_USE_DEMO_CONTENT=true
VITE_PRINCIPLES_DOC_ENABLED=true
VITE_PRIMARY_PERSPECTIVE_ENABLED=true

# Debug
VITE_DEBUG_OVERLAY=false

# Development
NODE_ENV=development
EOF

echo "✅ Created .env.local with development settings"
echo ""
echo "To enable the new living document UI:"
echo "  - VITE_PRINCIPLES_DOC_MODE=true (already set)"
echo "  - VITE_USE_HARDCODED_DATA=true (already set)"
echo ""
echo "Restart your development server to apply changes:"
echo "  npm run dev"
echo ""
echo "Visit http://localhost:5173/compass/hardcoded-1 to see the new UI"
