export const principlesDocCopy = {
  headerTag: 'Principle',
  communityDocTitle: 'Community document',
  counterDocTitle: 'Counter-document',
  livingPill: 'Living document',
  composerTitle: 'Share a revision or counterpoint',
  composerPlaceholder: 'Propose a change, add a nuance, or argue a counter-point. Focus on clarity and long-term implications…',
  composerTargetLabel: 'Target',
  targetMain: 'Community',
  targetCounter: 'Counter',
  targetNeutral: 'Neutral',
  post: 'Post revision',
  minMax: 'Short note. 240–1000 characters.',
  evidenceTitle: 'About this',
  evidenceEmpty: 'No sources listed yet.',
  suggestSource: 'Suggest a source',
  reasoningTitle: 'Recent proposals',
  readMore: 'Read more',
  readLess: 'Hide',
  developThisView: 'Develop this view',
  lastUpdated: 'Last updated',
  share: 'Share',
  created: 'Created',
  updated: 'Updated',
  labels: 'Labels',
  noLabels: 'No labels',
  retry: 'Retry',
  loading: 'Loading...',
  error: 'Error loading content',
  revisionPosted: 'Revision posted successfully',
  revisionError: 'Failed to post revision',
};
