export const principlesCopy = {
  livingLabel: 'Living document',
  communityDoc: {
    title: 'Community document',
    readMore: 'Read more',
  },
  counterDoc: {
    title: 'Counter-document',
    develop: 'Develop this view',
    readMore: 'Read more',
  },
  composer: {
    heading: 'Share a revision or counterpoint',
    placeholder:
      'Propose a change, add a nuance, or argue a counter-point. Focus on clarity and long-term implications…',
    helper: 'Short note. 240–1000 characters.',
    targetLabel: 'Target',
    target: {
      community: {
        label: 'Community',
        tooltip: 'Suggest a change to the Community document.',
        cta: 'Post revision to Community doc',
      },
      counter: {
        label: 'Counter',
        tooltip: 'Add to or argue for the Counter-document.',
        cta: 'Post addition to Counter-doc',
      },
      neutral: {
        label: 'Neutral',
        tooltip: 'Share a general note; editors can route it later.',
        cta: 'Post note (neutral)',
      },
    },
  },
  subviews: {
    revisions: 'Revisions',
    discussion: 'Discussion',
  },
  about: {
    heading: 'About this',
    suggest: 'Suggest a source',
    noSummary: 'No summary yet.',
    stance: {
      supports: 'Supports',
      questions: 'Questions',
      mixed: 'Mixed findings',
    },
  },
  // Legacy support
  headerTag: 'Principle',
  communityDocTitle: 'Community document',
  counterDocTitle: 'Counter-document',
  livingPill: 'Living document',
  composerTitle: 'Share a revision or counterpoint',
  composerPlaceholder: 'Propose a change, add a nuance, or argue a counter-point. Focus on clarity and long-term implications…',
  composerTargetLabel: 'Target',
  targetMain: 'Community',
  targetCounter: 'Counter',
  targetNeutral: 'Neutral',
  post: 'Post revision',
  minMax: 'Short note. 240–1000 characters.',
  evidenceTitle: 'About this',
  evidenceEmpty: 'No sources listed yet.',
  suggestSource: 'Suggest a source',
  reasoningTitle: 'Recent proposals',
  readMore: 'Read more',
  readLess: 'Hide',
  developThisView: 'Develop this view',
  lastUpdated: 'Last updated',
  share: 'Share',
  created: 'Created',
  updated: 'Updated',
  labels: 'Labels',
  noLabels: 'No labels',
  retry: 'Retry',
  loading: 'Loading...',
  error: 'Error loading content',
  revisionPosted: 'Revision posted successfully',
  revisionError: 'Failed to post revision',
};
